version: "3.8"
services:
  app1:
    build: ./app
    container_name: app1
    networks:
      - balancer-net

  app2:
    build: ./app2
    container_name: app2
    networks:
      - balancer-net

  nginx:
    image: nginx:stable
    container_name: nginx-balancer
    depends_on:
      - app1
      - app2
    volumes:
      - ./nginx/balancer.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    networks:
      - balancer-net

networks:
  balancer-net:
    driver: bridge
